spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver #my sql driver name
    url: jdbc:mysql://localhost:3306/userDatabase #mysql server url
    username: root #mysql username
    password: beyondm #mysql password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
